spring.application.name=online-exam
server.port=${SERVER_PORT:8080}

spring.datasource.url=jdbc:h2:mem:online_exam;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/demo-schema.sql
spring.sql.init.data-locations=classpath:sql/demo-data.sql

mybatis.configuration.map-underscore-to-camel-case=true
spring.thymeleaf.cache=false
spring.h2.console.enabled=true
